

class DbBotResponses:
    def __init__(self, collection):
        self.collection = collection

    def get(self, subreddit):
        return self.collection.find_one({'subreddit': subreddit})

    def add_default(self, subreddit):
        self.collection.insert_one({
            "final": "Thanks for your patience, a human moderator will review "
                     "the responses and respond to your request soon",
            "form_link": "https://appealmod.com/form/",
            "initial": "Hi! This message is generated by an automated bot. "
                       "If you would like the mods to reconsider your ban, "
                       "please fill out this quick "
                       "[form](https://appealmod.com/form/).",
            "reminder": "Just a reminder that any messages you send here will "
                        "not be read by a human until you have filled out the "
                        "[form](https://appealmod.com/form/).",
            'subreddit': subreddit,
        })
