# Generated by Django 5.0.6 on 2024-07-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_banappealdata_allowed_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banappealdata',
            name='why_appealing',
            field=models.CharField(choices=[('disagree', "I don't agree with the rule"), ('not-apply', "I don't think the rule applies to my behavior"), ('regret', 'I regret my behavior'), ('other', 'Other')], default=None, max_length=254, null=True, verbose_name='Why are you appealing your ban?'),
        ),
        migrations.AlterField(
            model_name='banappealdata',
            name='will_not_repeat',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default=None, max_length=10, null=True, verbose_name='Are you willing to pledge that you will not repeat such actions in the future?<br/> Repeated violations will lead to your profile being reported to Reddit administrators'),
        ),
        migrations.AlterField(
            model_name='banappealdata',
            name='wrong_actions',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default=None, max_length=10, null=True, verbose_name='Do you think your actions were wrong?'),
        ),
    ]
