# Generated by Django 5.0.6 on 2024-07-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_banappealdata_why_appealing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='subreddit_url',
            field=models.URLField(max_length=254),
        ),
    ]
