# Generated by Django 5.0.6 on 2024-07-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanAppealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_username', models.CharField(max_length=254)),
                ('subreddit', models.CharField(max_length=254)),
                ('why_banned', models.TextField()),
                ('why_appealing', models.TextField()),
                ('describe_rule', models.TextField()),
                ('describe_actions', models.TextField()),
                ('wrong_actions', models.BooleanField()),
                ('will_not_repeat', models.BooleanField()),
                ('what_steps', models.TextField()),
                ('allowed_comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'main_ban_appeal_data',
            },
        ),
    ]
