# Generated by Django 5.0.6 on 2024-07-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banappealdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banappealdata',
            name='allowed_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banappealdata',
            name='describe_actions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banappealdata',
            name='describe_rule',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banappealdata',
            name='what_steps',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banappealdata',
            name='why_appealing',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banappealdata',
            name='why_banned',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banappealdata',
            name='will_not_repeat',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='banappealdata',
            name='wrong_actions',
            field=models.BooleanField(null=True),
        ),
    ]
