# Generated by Django 5.0.6 on 2024-07-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_banappealdata_allowed_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banappealdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
