# Generated by Django 5.0.6 on 2024-07-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_banappealdata_why_appealing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banappealdata',
            name='why_appealing_other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
